{% set data = load_setup_py_data() %}


package:
  name: rec_to_nwb
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/NovelaNeuro/rec_to_nwb

build:
  number: 0

requirements:
   build:
      - python>=3.6
      - pip
      - setuptools
      - hdmf==1.6.1
      - libblas
      - pynwb==1.3.0
      - testfixtures
      - vdom
      - xmlschema
      - hdf5
      - liblapack
      - elementpath
      - rec_to_binaries==0.5.1.dev0
      - libcblas
   run:
      - python>=3.6
      - asn1crypto
      - blas
      - bleach
      - ca-certificates
      - certifi
      - cffi
      - chardet
      - cryptography
      - elementpath
      - h5py
      - hdf5
      - hdmf==1.6.1
      - idna
      - libblas
      - libcblas
      - liblapack
      - mkl
      - mkl-service
      - mountainlab_pytools
      - numpy
      - openssl
      - pandas
      - pip
      - pycparser
      - pynwb==1.3.0
      - pyopenssl
      - pysocks
      - pytest
      - python-dateutil
      - pytz
      - pyyaml
      - requests
      - scipy
      - setuptools
      - six
      - sqlite
      - testfixtures
      - urllib3
      - vdom
      - jp_proxy_widget
      - wheel
      - xmlschema
      - zlib
      - rec_to_binaries==0.5.1.dev0
      - xmldiff
      - ndx-franklab-novela=0.0.009


about:
  home: https://github.com/NovelaNeuro/rec_to_nwb
  license: "Apache 2.0"
  summary: "Tool used to transform data stored in SpikeGadgets raw files into nwb files"