{% set data = load_setup_py_data() %}


package:
  name: fldatamigration
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/NovelaNeuro/fldatamigration

build:
  number: 0

requirements:
   build:
      - python=3.7.4
      - pip
      - setuptools
   run:
      - asn1crypto=1.3.0
      - blas=1.0
      - bleach=3.1.4
      - ca-certificates=2020.1.1
      - certifi=2019.11.28
      - cffi=1.14.0
      - chardet=3.0.4
      - cryptography=2.8
      - elementpath=1.4.3
      - h5py=2.10.0
      - hdf5=1.10.5
      - hdmf=1.6.1
      - idna=2.9
      - libblas=3.8.0
      - libcblas=3.8.0
      - liblapack=3.8.0
      - mkl=2019.4
      - mkl-service=2.3.0
      - mountainlab_pytools=0.7.5
      - numpy=1.18.1
      - openssl=1.1.1e
      - pandas=1.0.3
      - pip=20.0.2
      - pycparser=2.20
      - pynwb=1.3.0
      - pyopenssl=19.1.0
      - pysocks=1.7.1
      - pytest=5.4.1
      - python=3.7.4
      - python-dateutil=2.8.0
      - pytz=2019.3
      - pyyaml=5.3.1
      - requests=2.23.0
      - scipy=1.3.1
      - setuptools=46.1.3
      - six=1.14.0
      - sqlite=3.30.1
      - testfixtures=6.14.0
      - urllib3=1.25.7
      - vdom=0.6
      - wheel=0.34.2
      - xmlschema=1.1.1
      - zlib=1.2.11
      - ndx-fllab-novela==0.0.7
      - pdoc==0.3.2
      - pyvalid==0.9.2
      - rec-to-binaries==0.3.0.dev0
      - xmldiff==2.4

about:
  home: https://github.com/NovelaNeuro/fldatamigration
  license: "Apache 2.0"
  summary: "Tool used to transform data stored in SpikeGadgets raw files into nwb files"