{% set data = load_setup_py_data() %}


package:
  name: fldatamigration
  version: {{ data.get('version') }}

source:
  path: ../fldatamigration

build:
  number: 0

outputs:
    files:
      - meta.yaml
      - pylintrc
      - README.md
      - setup.py
      - pylint-run.sh
      - bld.bat
      - build.sh
      - sonar-project.properties
      - fl/data
      - fl/datamigration
      - fl/notebooks
      - fl/scripts
      - fl/logging.conf
      - fl/environment.yml

requirements:
  build:
    - python=3.7.4
    - pip
    - setuptools

  run:
    - python=3.7.4

about:
  home: https://github.com/NovelaNeuro/fldatamigration
  license: "Apache 2.0"
  summary: "Tool used to transform data stored in SpikeGadgets raw files into nwb files"